# Small Cs-137 decay example run.
# Use with: baseLab -r on -b macros/run-decay-cs137.mac

/baseLab/geometry/worldSize 2.5 m
/baseLab/geometry/sampleDepth 10 cm
/baseLab/geometry/sampleRadius 5 cm
/baseLab/geometry/sampleThickness 1 mm
/control/macroPath .:macros:../macros

/baseLab/output/tag run-decay-cs137
/baseLab/output/geometry waterbox
/baseLab/output/region sample
/baseLab/output/depth 10 cm

/run/initialize

/control/execute source-cs137.mac

/gps/pos/type Point
/gps/pos/centre 0 0 -0.75 m
/gps/ang/type iso

/run/printProgress 20
/run/beamOn 200
